name: 'dotnet tools for use with actions'
description: 'dotnet tools for use with actions'
author: 'ZhaiSoul'

runs:
  using: "composite"
  steps:
    - id: Reactor
      run: ".NET Reactor/dotNET_Reactor.Console.exe" $REACTOR_ARG
      shell: cmd
     
    - id: CodeSign
      run: CodeSign/CodeSignTool.bat $CODESIGN_ARG
      shell: cmd
