name: 'dotnet tools for use with actions'
description: 'dotnet tools for use with actions'
author: 'ZhaiSoul'

runs:
  using: "composite"
  steps:
    - name: Reactor
      run: |
        cd %GITHUB_ACTION_PATH%
        cd Reactor
        dotNET_Reactor.Console.exe $REACTOR_ARG
      shell: cmd
     
    - name: CodeSign
      run: |
        cd %GITHUB_ACTION_PATH%
        cd CodeSign
        CodeSignTool.bat $CODESIGN_ARG
      shell: cmd
