name: 'dotnet tools for use with actions'
description: 'dotnet tools for use with actions'
author: 'ZhaiSoul'

runs:
  using: "composite"
  steps:
    - id: Reactor
      run: $GITHUB_ACTION_PATH/.NET Reactor/dotNET_Reactor.Console.exe $REACTOR_ARG
      shell: cmd
     
    - id: CodeSign
      run: $GITHUB_ACTION_PATH/CodeSign/CodeSignTool.bat $CODESIGN_ARG
      shell: cmd
